---
abstract: 'qw for array/hash references'
author:
  - 'Lukas Mai <l.mai@web.de>'
build_requires:
  Test::More: 0
  strict: 0
configure_requires:
  ExtUtils::MakeMaker: 6.56
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Quote-Ref
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  XSLoader: 0
  perl: 5.012000
  warnings: 0
resources: {}
version: 0.01
